# Generated by Django 3.2.9 on 2021-12-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='frequency',
            field=models.TextField(blank=True, db_column='Frequency', null=True),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='merchant',
            field=models.TextField(blank=True, db_column='Merchant', null=True),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='remarks',
            field=models.TextField(blank=True, db_column='Remarks', null=True),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='report',
            field=models.TextField(blank=True, db_column='Report', null=True),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='status',
            field=models.TextField(blank=True, db_column='Status', null=True),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='type',
            field=models.TextField(blank=True, db_column='Type', null=True),
        ),
        migrations.AlterModelTable(
            name='scraping',
            table='Scraping',
        ),
    ]
