# Generated by Django 3.2.9 on 2021-12-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0002_auto_20211206_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraping',
            table=None,
        ),
    ]
