# Generated by Django 3.2.9 on 2021-12-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0004_auto_20211206_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scraping',
            new_name='Logs',
        ),
    ]
