# Generated by Django 3.1.1 on 2021-12-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0007_logs_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='date_created',
        ),
    ]
