# Generated by Django 3.1.1 on 2021-12-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0008_remove_logs_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='report',
        ),
        migrations.AddField(
            model_name='logs',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdeventures.tasks'),
        ),
    ]
