# Generated by Django 3.1.1 on 2021-12-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdeventures', '0009_auto_20211214_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='d1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
